- hosts: localhost
  tasks:
    - import_role:
        name: karmab.kcli-modules
    - name: Get ip from vm tahitibob
      kcli_info: 
        name: tahitibob
      register: result
    - debug: var=result.meta.ip
